=== sorydima/Marina.Rodeo/doc/dbschema/dtd/dbschema.dtd
<!--
 * XSL converter script for common definitions
 *
 * Copyright (C) 2001-2007 FhG Fokus
 *
 * This file is part of openMarinkaRodeo, a free SIP server.
 *
 * openMarinkaRodeo is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version
 *
 * openMarinkaRodeo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software 
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 */
-->

<!ELEMENT database (name, description?, table*)>
<!ATTLIST database
    id ID #IMPLIED
>

<!ELEMENT name (#PCDATA) >

<!ELEMENT description (#PCDATA) >

<!ELEMENT table (name, description?, version?, column+, index*, row*) >
<!ATTLIST table
    id ID #IMPLIED
>

<!ELEMENT version (#PCDATA) >

<!ELEMENT column (name, description?, type, size?, default?, null?, primary?, natural?, autoincrement?) >
<!ATTLIST column
    id ID #IMPLIED
>

<!ELEMENT index (name?, unique?, primary?, colref+) >
<!ATTLIST index
    id ID #IMPLIED
>

<!ELEMENT type (#PCDATA) >

<!ELEMENT size (#PCDATA) >

<!ELEMENT default (#PCDATA) >

<!ELEMENT null EMPTY >

<!ELEMENT unique EMPTY >

<!ELEMENT primary EMPTY >

<!ELEMENT natural EMPTY >

<!ELEMENT autoincrement EMPTY >

<!ELEMENT colref EMPTY>
<!ATTLIST colref
    linkend IDREF #REQUIRED
>

=== sorydima/Marina.Rodeo/db/schema/address.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//openMarinkaRodeo.org//DTD DBSchema V1.1//EN" 
  "https://openMarinkaRodeo.org/pub/openMarinkaRodeo/dbschema/dtd/1.1/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table id="address" xmlns:db="http://docbook.org/ns/docbook">
	<name>address</name>
	<version>5</version>
	<type db="mysql">&MYSQL_TABLE_TYPE;</type>
	<description>
		<db:para>This table is used by the permissions module. More information is available at: &OPENMarinkaRodeo_MOD_DOC;permissions.html
		</db:para>
	</description>

	<column id="id">
		<name>id</name>
		<type>unsigned int</type>
		<size>&table_id_len;</size>
		<autoincrement/>
		<primary/>
		<type db="dbtext">int,auto</type>
		<description>unique ID</description>
	</column>

	<column>
		<name>grp</name>
		<type>unsigned short</type>
		<size>5</size>
		<default>0</default>
		<description>The group ID - each address may belong to a group/set</description>
		<natural/>
	</column>

	<column id="ip">
		<name>ip</name>
		<type>string</type>
		<size>&ip_add_len;</size>
		<description>IP address, IPv4 or IPv6 format</description>
		<natural/>
	</column>

	<column>
		<name>mask</name>
		<type>char</type>
		<default>32</default>
		<description>Network mask, a number from 0 to 128; It should be up to 32 if the IP is v4 and up to 128 if the IP is v6</description>
	</column>

	<column>
		<name>port</name>
		<type>unsigned short</type>
		<size>5</size>
		<default>0</default>
		<description>Port number, 0 value meaning 'any' (wildcard)</description>
	</column>

	<column>
		<name>proto</name>
		<type>string</type>
		<size>4</size>
		<default>any</default>
		<description>Transport protocol is either "any" or equal to transport protocol of request. Possible values that can be stored are "any", "udp", "tcp", "tls", and "sctp".</description>
	</column>

	<column>
		<name>pattern</name>
		<type>string</type>
		<size>&id_len;</size>
		<default><null/></default>
		<null/>
		<description>A shell wildcard pattern to be used for matching string provided by the check address functions.</description>
	</column>

	<column>
		<name>context_info</name>
		<type>string</type>
		<size>32</size>
		<default><null/></default>
		<null/>
		<description>Extra context information, not used by OpenMarinkaRodeo, but simply exposed to the script level via scripting variables</description>
	</column>
</table>

=== sorydima/Marina.Rodeo/db/schema/auth_jwt_secrets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//openMarinkaRodeo.org//DTD DBSchema V1.1//EN" 
  "https://openMarinkaRodeo.org/pub/openMarinkaRodeo/dbschema/dtd/1.1/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table id="jwt_secrets" xmlns:db="http://docbook.org/ns/docbook">
	<name>jwt_secrets</name>
	<version>1</version>
	<type db="mysql">&MYSQL_TABLE_TYPE;</type>
	<description>
		<db:para>This table is used by the AUTH_JWT module to read the actual JWT secrets which are used for authentication
		More information can be found at: &OPENMarinkaRodeo_MOD_DOC;auth_jwt.html.
		</db:para>
	</description>

	<column id="id">
		<name>id</name>
		<type>unsigned int</type>
		<size>&table_id_len;</size>
		<autoincrement/>
		<natural/>
		<primary/>
		<type db="dbtext">int,auto</type>
		<description>Table key, not used by module</description>
	</column>

	<column id="corresponding_tag">
		<name>corresponding_tag</name>
		<type>string</type>
		<size>128</size>
		<description>JWT profile tag which this secret belongs to</description>
	</column>

	<column id="secret">
		<name>secret</name>
		<type>text</type>
		<description>The KEY used for signing the JWT
		</description>
	</column>

	<column id="start_ts">
		<name>start_ts</name>
		<type>int</type>
		<description>UNIX TS for the START period on which the JWT secret is valid
		</description>
	</column>

	<column id="end_ts">
		<name>end_ts</name>
		<type>int</type>
		<description>UNIX TS for the END period on which the JWT secret is valid
		</description>
	</column>

</table>

=== sorydima/Marina.Rodeo/db/schema/dbaliases.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//openMarinkaRodeo.org//DTD DBSchema V1.1//EN" 
  "https://openMarinkaRodeo.org/pub/openMarinkaRodeo/dbschema/dtd/1.1/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table id="dbaliases" xmlns:db="http://docbook.org/ns/docbook">
    <name>dbaliases</name>
    <version>2</version>
    <type db="mysql">&MYSQL_TABLE_TYPE;</type>
    <description>
        <db:para>This table us used by the alias_db module as an alternative for user aliases via userloc. More information about the alias_db module can be found at: &OPENMarinkaRodeo_MOD_DOC;alias_db.html
        </db:para>
    </description>

    <column id="id">
        <name>id</name>
        <type>unsigned int</type>
        <size>&table_id_len;</size>
        <autoincrement/>
        <primary/>
        <type db="dbtext">int,auto</type>
        <description>unique ID</description>
    </column>

    <column id="alias_username">
        <name>alias_username</name>
        <type>string</type>
        <size>&user_len;</size>
        <default/>
        <description>Alias username / phone number</description>
        <natural/>
    </column>

    <column id="alias_domain">
        <name>alias_domain</name>
        <type>string</type>
        <size>&domain_len;</size>
        <default/>
        <description>Alias domain name</description>
        <natural/>
    </column>

    <column id="username">
        <name>&USERCOL;</name>
        <type>string</type>
        <size>&user_len;</size>
        <default/>
        <description>Username / phone number</description>
    </column>

    <column id="domain">
        <name>domain</name>
        <type>string</type>
        <size>&domain_len;</size>
        <default/>
        <description>Domain name</description>
    </column>

    <index>
        <name>alias_idx</name>
        <colref linkend="alias_username"/>
        <colref linkend="alias_domain"/>
        <unique/>
    </index>

    <index>
        <name>target_idx</name>
        <colref linkend="username"/>
        <colref linkend="domain"/>
    </index>
</table>

=== sorydima/Marina.Rodeo/db/schema/load_balancer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//openMarinkaRodeo.org//DTD DBSchema V1.1//EN" 
  "https://openMarinkaRodeo.org/pub/openMarinkaRodeo/dbschema/dtd/1.1/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table id="load_balancer" xmlns:db="http://docbook.org/ns/docbook">
	<name>load_balancer</name>
	<version>3</version>
	<type db="mysql">&MYSQL_TABLE_TYPE;</type>
	<description>
		<db:para>This table is used by the Load-Balancer module to store
		information about the destinations the balance the calls between.
		More information can be found at: &OPENMarinkaRodeo_MOD_DOC;load_balancer.html.
		</db:para>
	</description>

	<column id="id">
		<name>id</name>
		<type>unsigned int</type>
		<size>&table_id_len;</size>
		<autoincrement/>
		<primary/>
		<type db="dbtext">int,auto</type>
		<description>unique ID of the destination
		</description>
	</column>

	<column id="group_id">
		<name>group_id</name>
		<type>unsigned int</type>
		<size>11</size>
		<default>0</default>
		<description>The group the destination belongs to</description>
	</column>

	<column id="dst_uri">
		<name>dst_uri</name>
		<type>string</type>
		<natural/>
		<size>128</size>
		<description>Destination address as a SIP URI</description>
	</column>

	<column id="resources">
		<name>resources</name>
		<type>string</type>
		<size>255</size>
		<description>String with the definition of the resource provided
		by the destination and the capacity of each resource</description>
	</column>

	<column id="probe_mode">
		<name>probe_mode</name>
		<type>unsigned int</type>
		<size>11</size>
		<default>0</default>
		<description>Probing mode (0-none, 1-if disabled, 2-all the time)</description>
	</column>

	<column id="attrs">
		<name>attrs</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<default><null/></default>
		<description>Attribute string - custom, opaque string that
		will simply be pushed into script</description>
	</column>

	<column id="description">
		<name>description</name>
		<type>string</type>
		<size>128</size>
		<null/>
		<default><null/></default>
		<description>Text description of the destination</description>
	</column>

	<index>
		<name>dsturi_idx</name>
		<colref linkend="dst_uri"/>
	</index>

</table>

=== sorydima/Marina.Rodeo/db/schema/fraud_detection.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//openMarinkaRodeo.org//DTD DBSchema V1.1//EN" 
  "https://openMarinkaRodeo.org/pub/openMarinkaRodeo/dbschema/dtd/1.1/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table id="fraud_detection" xmlns:db="http://docbook.org/ns/docbook">
	<name>fraud_detection</name>
	<version>1</version>
	<type db="mysql">&MYSQL_TABLE_TYPE;</type>
	<description>
		<db:para>This table is used by the Fraud Detection module to store
		information about fraud-profiles.
		More information can be found at: &OPENMarinkaRodeo_MOD_DOC;fraud_detection.html.
		</db:para>
	</description>

	<column id="ruleid">
		<name>ruleid</name>
		<type>unsigned int</type>
		<size>&table_id_len;</size>
		<autoincrement/>
		<natural/>
		<primary/>
		<type db="dbtext">int,auto</type>
		<description>Rule unique ID
		</description>
	</column>

	<column id="profileid">
		<name>profileid</name>
		<type>unsigned int</type>
		<description>The ID of the profile the current rule is part of
		</description>
	</column>

	<column id="prefix">
		<name>prefix</name>
		<type>string</type>
		<size>64</size>
		<description>Numerical prefix to match this rule</description>
	</column>

	<column id="start_hour">
		<name>start_hour</name>
		<type>string</type>
		<size>5</size>
		<default>00:00</default>
		<description>Start of the interval in which the rule should be matched.
		</description>
	</column>

	<column id="end_hour">
		<name>end_hour</name>
		<type>string</type>
		<size>5</size>
		<default>23:59</default>
		<description>End of the interval in which the rule should be matched.
		</description>
	</column>

	<column id="daysoftheweek">
		<name>daysoftheweek</name>
		<type>string</type>
		<size>64</size>
		<default>Mon-Sun</default>
		<description>List/interval of days in which the rule is available.
		</description>
	</column>

	<column id="cpm_warning">
		<name>cpm_warning</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description>Warning threshold for calls per minute.</description>
	</column>
	
	<column id="cpm_critical">
		<name>cpm_critical</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description>Crtical threshold for calls per minute.</description>
	</column>
	
	<column id="call_duration_warning">
		<name>call_duration_warning</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description>Warning threshold for calls per minute.</description>
	</column>
	
	<column id="call_duration_critical">
		<name>call_duration_critical</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description>Crtical threshold for call duration.</description>
	</column>
		
	<column id="total_calls_warning">
		<name>total_calls_warning</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description>Warning threshold for total calls.</description>
	</column>
	
	<column id="total_calls_critical">
		<name>total_calls_critical</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description>Crtical threshold for total calls.</description>
	</column>
			
	<column id="concurrent_calls_warning">
		<name>concurrent_calls_warning</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description>Warning threshold for concurrent calls.</description>
	</column>
	
	<column id="concurrent_calls_critical">
		<name>concurrent_calls_critical</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description>Crtical threshold for concurrent calls.</description>
	</column>
			
	<column id="sequential_calls_warning">
		<name>sequential_calls_warning</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description>Warning threshold for sequential calls.</description>
	</column>
	
	<column id="sequential_calls_critical">
		<name>sequential_calls_critical</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description>Crtical threshold for sequential calls.</description>
	</column>

</table>

=== sorydima/Marina.Rodeo/db/schema/dr_partitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//openMarinkaRodeo.org//DTD DBSchema V1.1//EN" 
  "https://openMarinkaRodeo.org/pub/openMarinkaRodeo/dbschema/dtd/1.1/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table id="dr_partitions" xmlns:db="http://docbook.org/ns/docbook">
	<name>dr_partitions</name>
	<version>1</version>
	<type db="mysql">&MYSQL_TABLE_TYPE;</type>
	<description>
		<db:para>This table is used by the Dynamic Routing module to store
		information about the partitions used in routing (url to database, 
		table names and AVP names for each partition).
		More information can be found at: &OPENMarinkaRodeo_MOD_DOC;drouting.html.
		</db:para>
	</description>

	<column id="id">
		<name>id</name>
		<type>unsigned int</type>
		<size>&table_id_len;</size>
		<autoincrement/>
		<natural/>
		<primary/>
		<type db="dbtext">int,auto</type>
		<description>Partition unique ID
		</description>
	</column>

	<column id="partition_name">
		<name>partition_name</name>
		<type>string</type>
		<size>255</size>
		<description>The name of the partition.
		</description>
	</column>

	<column id="db_url">
		<name>db_url</name>
		<type>string</type>
		<size>255</size>
		<description>The url to the database containing the tables: dr_rules, dr_groups,
		dr_carriers and dr_gateways</description>
	</column>

	<column id="drd_table">
		<name>drd_table</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of the dr_gateways table in the given database (for the given partition).</description>
	</column>

	<column id="drr_table">
		<name>drr_table</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of the dr_rules table in the given database (for the given partition).</description>
	</column>

	<column id="drg_table">
		<name>drg_table</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of the dr_groups table in the given database (for the given partition).</description>
	</column>

	<column id="drc_table">
		<name>drc_table</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of the dr_carriers table in the given database (for the given partition).</description>
	</column>

	<column id="ruri_avp">
		<name>ruri_avp</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of ruri_avp AVP.</description>
	</column>

	<column id="gw_id_avp">
		<name>gw_id_avp</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of gw_id_avp AVP</description>
	</column>

	<column id="gw_priprefix_avp">
		<name>gw_priprefix_avp</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of gw_priprefix_avp AVP.</description>
	</column>

	<column id="gw_sock_avp">
		<name>gw_sock_avp</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of gw_sock_avp AVP.</description>
	</column>
	
	<column id="rule_id_avp">
		<name>rule_id_avp</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of rule_id_avp AVP.</description>
	</column>
	
	<column id="rule_prefix_avp">
		<name>rule_prefix_avp</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of rule_prefix_avp AVP.</description>
	</column>
	
	<column id="carrier_id_avp">
		<name>carrier_id_avp</name>
		<type>string</type>
		<size>255</size>
		<null/>
		<description>The name of carrier_id_avp AVP.</description>
	</column>

</table>

=== sorydima/Marina.Rodeo/db/schema/emergency_report.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//openMarinkaRodeo.org//DTD DBSchema V1.1//EN" 
  "https://openMarinkaRodeo.org/pub/openMarinkaRodeo/dbschema/dtd/1.1/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table id="emergency_report" xmlns:db="http://docbook.org/ns/docbook">
	<name>emergency_report</name>
	<version>1</version>
	<type db="mysql">&MYSQL_TABLE_TYPE;</type>
	<description>
		<db:para>This table is used by the Emergency module to save information associated 
		  with a emergency call, for trouble shooting purposes.
		  More information can be found at: &OPENMarinkaRodeo_MOD_DOC;emergency.html.
		</db:para>
	</description>

	<column id="id">
		<name>id</name>
		<type>unsigned int</type>
		<size>&table_id_len;</size>
		<autoincrement/>
		<natural/>
		<primary/>
		<type db="dbtext">int,auto</type>
		<description>Unique ID</description>
	</column>

	<column id="callid">
		<name>callid</name>
		<type>string</type>
		<size>25</size>
		<description> header that uniquely identifies the call.
		</description>
	</column>

	<column id="selectiveRoutingID">
		<name>selectiveRoutingID</name>
		<type>string</type>
		<size>11</size>
		<description>The Common Language Location Indicator(CLLI) code associated
		  with the Selective Router to which the emergency call is to be directed
		</description>
	</column>

	<column id="routingESN">
		<name>routingESN</name>
		<type>unsigned int</type>
		<size>5</size>
		<default>0</default>
		<description> The Emergency Services Number associated with a particular ESZ 
		  that respresents a unique combination of Police, Fire and EMS emergency responders.
		</description>
	</column>

	<column id="npa">
		<name>npa</name>
		<type>unsigned int</type>
		<size>3</size>
		<default>0</default>
		<description> The primary Numbering Plan Area (NPA) associated with 
		the outgoing route to the Selective Router that is appropriate for 
		caller's location.
		</description>
	</column>

	<column id="esgwri">
		<name>esgwri</name>
		<type>string</type>
		<size>50</size>
		<description> Routing information used to direct the call to the ESGW.
		</description>
	</column>

	<column id="lro">
		<name>lro</name>
		<type>string</type>
		<size>20</size>
		<description>last routing option destination for the call.
		</description>
	</column>

	<column id="VPC_organizationName">
		<name>VPC_organizationName</name>
		<type>string</type>
		<size>50</size>
		<description> company name or other label of the VPC that provided the routing information.
		</description>
	</column>

	<column id="VPC_hostname">
		<name>VPC_hostname</name>
		<type>string</type>
		<size>50</size>
		<description> identifies the fully qualified domain name or IP address
		  of the VPC that provided routing information.
		</description>
	</column>

	<column id="VPC_timestamp">
		<name>VPC_timestamp</name>
		<type>string</type>
		<size>30</size>
		<description>Date Time Stamp indicating UTC date and time that the message was sent from VPC.
		</description>
	</column>

	<column id="result">
		<name>result</name>
		<type>string</type>
		<size>4</size>
		<description> Code indicating the reason for success or failure to determine an ERT/ESGWRI and ESQK.
		</description>
	</column>

	<column id="disposition">
		<name>disposition</name>
		<type>string</type>
		<size>10</size>
		<description> Describe how routing of call was done(e.g.,by ESGWRI or bye LRO)
		</description>
	</column>
</table>
